### ISSUE TITLE
Am I doing it wrong?

### ISSUE THREAD

**Issue by amoore2600** [GoobyCorp/RetroFreak_Toolkit#1]
amoore@amoore-OptiPlex-7010:~$ /home/amoore/Downloads/RetroFreakROM.py -h 
Traceback (most recent call last):
  File "/home/amoore/Downloads/RetroFreakROM.py", line 108, in <module>
    main()
  File "/home/amoore/Downloads/RetroFreakROM.py", line 88, in main
    REQUEST_PUB_KEY = RSA.import_key(read_file(join("Keys", REQUEST_PUB_KEY_FILE)))
  File "/home/amoore/Downloads/RetroFreakROM.py", line 26, in read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Keys/request.pub'

what do I need to do?

**Comment by GoobyCorp** [comment]
Sorry about that, put [this](https://ishr.ink/wgrfnuqg) next to the script
