### ISSUE TITLE
Similar issue to amoore2600?

### ISSUE THREAD

**Issue by koodhii** [GoobyCorp/RetroFreak_Toolkit#2]
I'm getting the exact same error message as #1, but I'm using the most recent commit.

`C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master>RetroFreakROM.py -h
Traceback (most recent call last):
  File "C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master\RetroFreakROM.py", line 123, in <module>
    main()
  File "C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master\RetroFreakROM.py", line 92, in main
    REQUEST_PUB_KEY = RSA.import_key(read_file(join("Keys", REQUEST_PUB_KEY_FILE)))
  File "C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master\RetroFreakROM.py", line 29, in read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Keys\\request.pub'`

Same kind of thing with the RetroFreak.py file, too.

`C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master>RetroFreak.py -h
Traceback (most recent call last):
  File "C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master\RetroFreak.py", line 619, in <module>
    main()
  File "C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master\RetroFreak.py", line 595, in main
    UPDATE_PUB_KEY = RSA.import_key(read_file(join("Keys", UPDATE_PUB_KEY_FILE)))
  File "C:\Users\codyg\Desktop\RetroFreak\RetroFreak_Toolkit-master\RetroFreak.py", line 200, in read_file
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Keys\\update.pub'`

Python version is 3.9.0. Any idea about what the problem could be? Sorry for the trouble!

**Comment by GoobyCorp** [comment]
You need the RSA public keys for update requests and extracting updates.

**Comment by alpgarcia** [comment]
First, thanks for your work on this project, it's amazing!

The link on https://github.com/GoobyCorp/RetroFreak_Toolkit/issues/2#issuecomment-731912289 seems to be broken. May I ask if there is still any way to get the public keys?
